version: '3.4'
# usage example: http://localhost:81/users with the header Host user
services:
  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "81:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - http.services.user-service.loadbalancer.server.port=8001
      - http.services.message-service.loadbalancer.server.port=8002
      - http.services.event-service.loadbalancer.server.port=8000
    networks:
      - cogame-network

  user-service:
    image: cogame/user-service:0.0.1-SNAPSHOT # A container that exposes an API to show its IP address
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-service.rule=PathPrefix(`/users`) || Path(`/certain-users`) || Path(`/greeting`)
      - traefik.http.services.user-service.loadbalancer.server.port=8001
    networks:
      - cogame-network

  event-service:
    image: cogame/event-service:0.0.1-SNAPSHOT
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.event-service.rule=PathPrefix(`/events`)
        || Path(`/events/{a-zA-Z0-9+}/messages`)
        || Path(`/greeting`) && Host(`message`)
        || Path(`/events/{a-zA-Z0-9+}/users`)
        || Path(`/events/{a-zA-Z0-9+}/users/{a-zA-Z0-9+}`)
        || Path(`/greeting`) && Host(`event`)
      - traefik.http.services.event-service.loadbalancer.server.port=8000
    networks:
      - cogame-network

  message-service:
    image: cogame/message-service:0.0.1-SNAPSHOT # A container that exposes an API to show its IP address
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.message-service.rule=PathPrefix(`/messages`) || Path(`/events/{a-zA-Z0-9+}/messages`) || Path(`/greeting`) && Host(`message`)
      - traefik.http.services.message-service.loadbalancer.server.port=8002
    networks:
      - cogame-network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - cogame-network
networks:
  cogame-network: