version: '3.4'
# usage example: http://localhost:81/users
services:

  event-service:
    image: cogame/event-service:0.0.1-SNAPSHOT
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.event-service.rule=
        PathPrefix(`/events`)
        || Path(`/events/users/{a-zA-Z0-9+}/eventsTime`)
        || Path(`/events/users/{a-zA-Z0-9+}/fromAllEvents`)
        || Path(`/events/{a-zA-Z0-9+}/messages`)
        || Path(`/events/{a-zA-Z0-9+}/users`)
        || Path(`/events/{a-zA-Z0-9+}/users/{a-zA-Z0-9+}`)
        || Path(`/v2/api-docs`) && Host(`event`)
        || Path(`/events/{a-zA-Z0-9+}/users/{a-zA-Z0-9+}/participates`)
      # usage example: GET /events, /events/1; POST /events
      # usage example: GET /events/1/messages (makes web request to message-service)
      # usage example: PUT /events/1/users (adds user)
      # usage example: PUT /events/1/users/1 (deletes user)
      # usage example: GET /greeting with the header Host event
      # usage example: GET /v2/api-docs with the header Host event
      - traefik.http.services.event-service.loadbalancer.server.port=8000
      # middlewares
      - traefik.http.routers.event-service.middlewares=eventHeaders,eventAuth
      - traefik.http.middlewares.eventHeaders.headers.customrequestheaders.Service-Name=event
      - traefik.http.middlewares.eventAuth.forwardauth.address=http://authentication:8003
    networks:
      - cogame-network

  user-service:
    image: cogame/user-service:0.0.1-SNAPSHOT
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.user-service.rule=
        PathPrefix(`/users`)
        || Path(`/certain-users`)
        || Path(`/greeting`) && Host(`user`)
        || Path(`/v2/api-docs`) && Host(`user`)
        # usage example: GET /users, /users/1; POST /users
        # usage example: GET /certain-users (with request body ["1","57483875"])
        # usage example: GET /greeting with the header Host user
      # usage example: GET /v2/api-docs with the header Host user
      - traefik.http.services.user-service.loadbalancer.server.port=8001
      # middlewares
      - traefik.http.routers.user-service.middlewares=userHeaders,userAuth
      - traefik.http.middlewares.userHeaders.headers.customrequestheaders.Service-Name=user
      - traefik.http.middlewares.userAuth.forwardauth.address=http://authentication:8003
    networks:
      - cogame-network


  message-service:
    image: cogame/message-service:0.0.1-SNAPSHOT
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
      - traefik.http.routers.message-service.rule=
        PathPrefix(`/messages`)
        || Path(`/v2/api-docs`) && Host(`message`)
        || Path(`/ul`)
        # usage example: POST /messages
        # usage example: GET /greeting with the header Host user
      # usage example: GET /v2/api-docs with the header Host message
      - traefik.http.services.message-service.loadbalancer.server.port=8002
      # middlewares
      - traefik.http.routers.message-service.middlewares=messageHeaders,messageAuth
      - traefik.http.middlewares.messageHeaders.headers.customrequestheaders.Service-Name=message
      - traefik.http.middlewares.messageAuth.forwardauth.address=http://authentication:8003

    networks:
      - cogame-network

  authentication:
    image: cogame/authentication:0.0.1-SNAPSHOT
    env_file:
      - ./traefik.env
    labels:
      - traefik.enable=true
    networks:
      - cogame-network

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - cogame-network

  traefik:
    # The official v2 Traefik docker image
    image: traefik:v2.4
    # Enables the web UI and tells Traefik to listen to docker
    command:
      --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "81:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - http.services.user-service.loadbalancer.server.port=8001
      - http.services.message-service.loadbalancer.server.port=8002
      - http.services.event-service.loadbalancer.server.port=8000
    networks:
      - cogame-network
networks:
  cogame-network: